// src/assets/src/mediamanager/components/DropZone.vue
<template>
    <div class="alert bg-red-600 rounded font-medium mt-8 mb-4" v-if="alert">
        <div class="alert-items">
            <div class="alert-item flex gap-2 p-2 text-white justify-between">
                <div class="flex gap-2">
                    <div class="alert-icon-wrapper">
                        <i class="las la-exclamation-triangle text-sm"></i>
                    </div>
                    <span class="alert-text">{{ alert }}</span>
                </div>
                <div class="cursor-pointer" @click="alert = ''">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                    >
                        <path
                            fill="currentColor"
                            d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12L19 6.41Z"
                        ></path>
                    </svg>
                </div>
            </div>
        </div>
    </div>
    <div
        class="h-[106px] relative transition"
        :class="loading ? 'opacity-60' : ''"
    >
        <div
            @drop.prevent="onDrop"
            class="drop-zone"
            @click="fileInput.click()"
        >
            <span class="text-sm text-[#C6BBBB]">dropzone</span>
        </div>
        <input
            type="file"
            name=""
            id=""
            @input="onLoad"
            ref="fileInput"
            hidden="hidden"
            multiple
        />
        <span
            class="loader transition"
            :class="loading ? 'loader--active' : ''"
        ></span>
    </div>
</template>

<script setup>
import { inject, onMounted, onUnmounted, ref } from "vue";

const fileInput = ref(null);
const uploadUrl = inject("uploadUrl");
const group = inject("group");
const loading = ref(false);
const alert = ref("");

const pushData = inject("pushData");

async function onDrop(e) {
    loading.value = true;
    for (const file of e.dataTransfer.files) {
        await upload(file);
    }
}

async function onLoad(e) {
    for (const file of e.target.files) {
        loading.value = true;
        await upload(file);
    }
}

async function upload(file) {
    let form = new FormData();
    form.append("name", file.name);
    form.append("_method", "upload");
    form.append("group", group);
    form.append("file", file);
    let res = await ky.post(uploadUrl, { body: form }).json();
    console.log(res.data);
    if (res.msg === "success") {
        loading.value = false;
        pushData(res.data);
    } else {
        loading.value = false;
        alert.value = res.msg;
    }
}

function preventDefaults(e) {
    e.preventDefault();
}

const events = ["dragenter", "dragover", "dragleave", "drop"];

onMounted(() => {
    events.forEach((eventName) => {
        document.body.addEventListener(eventName, preventDefaults);
    });
});

onUnmounted(() => {
    events.forEach((eventName) => {
        document.body.removeEventListener(eventName, preventDefaults);
    });
});
</script>
<style scoped></style>

// src/assets/js/components/media-manager/components/DropZone.tsx
import React, {useState, useRef, FC, useContext} from 'react';
import {TriangleAlert, XIcon} from "lucide-react";
import styles from '@/components/media-manager/components/DropZone.module.css'
import axios from "axios";
import {MediaManagerContext} from "@/components/media-manager/media-manager.tsx";
import {Media} from "@/types";

interface DropZoneProps {
    callback: (media: Media) => void
    messages: Record<string, string>
}

const DropZone: FC<DropZoneProps> = ({callback, messages}) => {
    const fileInputRef = useRef<HTMLInputElement>(null);
    const [loading, setLoading] = useState<boolean>(false);
    const [alert, setAlert] = useState<string>('');

    const {uploadUrl, group} = useContext(MediaManagerContext);

    const handleClose = () => {
        setAlert('')
    }

    const onDrop = async (e: React.DragEvent<HTMLDivElement>) => {
        e.preventDefault();
        e.stopPropagation();
        setLoading(true);

        if (e.dataTransfer.files) {
            for (const file of e.dataTransfer.files) {
                await upload(file);
            }
        }
    };

    const onLoad = async (e: React.ChangeEvent<HTMLInputElement>) => {
        e.stopPropagation();
        if (e.target.files) {
            for (const file of e.target.files) {
                setLoading(true);
                await upload(file);
            }
        }
    };

    const upload = async (file: File) => {
        try {
            const form = new FormData();
            form.append("name", file.name);
            form.append("group", group);
            form.append("file", file);

            const res = await axios.post(`${uploadUrl}/upload`, form, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            });

            if (res.data.msg === "success") {
                setLoading(false);
                callback(res.data.data[0]);
                return;
            }

            setLoading(false);
            setAlert(res.data.error || "Upload failed");

        } catch (error) {
            setLoading(false);

            if (axios.isAxiosError(error)) {
                if (error.response) {
                    const errorMessage = error.response.data?.error ||
                        error.response.data?.message ||
                        error.response.statusText;
                    setAlert(errorMessage || `Error: ${error.response.status}`);
                } else if (error.request) {
                    setAlert("No response from server");
                } else {
                    setAlert("Request setup error");
                }
            } else {
                setAlert("Error uploading file");
                console.error(error);
            }
        }
    };

    return (
        <div className="mt-2">
            {alert &&
                <div className="bg-red-600 rounded font-medium mb-4">
                    <div className="flex gap-2 p-2 text-white justify-between">
                        <div className="flex gap-2">
                            <TriangleAlert/>
                            <span className="alert-text">{alert}</span>
                        </div>
                        <div onClick={handleClose}
                             className="cursor-pointer hover:opacity-80 transition-opacity">
                            <XIcon/>
                        </div>
                    </div>
                </div>
            }
            <div className="relative">
                <div
                    onDrop={onDrop}
                    onDragOver={(e) => e.preventDefault()}
                    className={`flex items-center justify-center w-full ${loading ? 'opacity-30' : ''}`}
                >
                    <label
                        htmlFor="dropzone-file"
                        className="flex flex-col items-center justify-center w-full h-32 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:bg-gray-700 dark:hover:bg-gray-600"
                    >
                        <div className="flex flex-col items-center justify-center pt-5 pb-6">
                            <svg className="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                                <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                                      d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
                            </svg>
                            <p className="mb-2 text-sm text-gray-500 dark:text-gray-400">
                                <span className="font-semibold">{messages["Click to upload or drag and drop"]}</span>
                            </p>
                        </div>
                        <input
                            id="dropzone-file"
                            key="dropzone-file"
                            type="file"
                            ref={fileInputRef}
                            onChange={onLoad}
                            className="hidden"
                            multiple
                            accept="*"
                        />
                    </label>
                </div>
                {loading && (
                    <span
                        className={`${styles.Loader} absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-6 h-6 border-3 border-solid border-gray-200 border-t-blue-500 rounded-full animate-spin`}
                    ></span>
                )}
            </div>
        </div>
    )
}
export default DropZone
