// src/assets/src/mediamanager/components/Tile.vue
<template>
    <div class="grid grid-cols-[repeat(auto-fill,_150px)] gap-2 justify-start">
        <Image
            :item="item"
            v-for="item in mediaList"
            init-class="w-full h-full max-w-[150px]"
            wrapper-class="max-w-[150px]"
            alt=""
        />
    </div>
</template>

<script>
export default {
    name: "Tile",
};
</script>

<script setup>
import Image from "./Image.vue";
const props = defineProps(["mediaList"]);
</script>

<style scoped></style>

// src/assets/js/components/media-manager/components/Tile.tsx
import {MediaProps} from "@/types";
import Image from "@/components/media-manager/components/Image.tsx";

const Tile = ({mediaList, messages, openMeta, crop, openVariant, destroy}: MediaProps) => {

    return (
        <div className="grid grid-cols-[repeat(auto-fill,_150px)] gap-2 justify-start">
            {mediaList.map((media) => (
                <div key={media.id}>
                    <Image media={media} messages={messages} openMeta={openMeta} crop={crop} openVariant={openVariant} destroy={destroy} className="max-w-[150px]"/>
                </div>
            ))}
        </div>
    )
}
export default Tile
