// src/assets/js/components/add-widgets.tsx
import {useCallback, useEffect, useState} from "react";
import {Widget} from "@/types";
import {Card, CardFooter, CardHeader, CardTitle} from "@/components/ui/card.tsx";
import MaterialIcon from "@/components/material-icon.tsx";
import {Button} from "@/components/ui/button.tsx";
import {Input} from "@/components/ui/input.tsx";

interface AddWidget {
    initWidgets: Widget[];
}

type WidgetGroup = Record<string, { items: Widget[], title: string }>;

type Head = { type: string, title: string };

const addWidgets = ({initWidgets}: AddWidget) => {
    const [widgets, setWidgets] = useState<WidgetGroup>({
        switchers: {items: [], title: ''},
        info: {items: [], title: ''},
        actions: {items: [], title: ''},
        links: {items: [], title: ''},
        custom: {items: [], title: ''}
    });

    const [head, setHead] = useState<Head[]>([]);
    const [filter, setFilter] = useState('');
    const [search, setSearch] = useState('');

    useEffect(() => {
        const newWidgets: WidgetGroup = {
            switchers: {items: [], title: ''},
            info: {items: [], title: ''},
            actions: {items: [], title: ''},
            links: {items: [], title: ''},
            custom: {items: [], title: ''}
        };
        const newHead: Head[] = [];

        for (const widget of initWidgets) {
            if (widget.type === 'switcher') {
                newWidgets.switchers.items.push(widget);
                if (newHead.find(e => e.type === 'switchers')) continue
                newWidgets.switchers.title = 'Switcher'
                newHead.push({type: 'switchers', title: 'Switcher'});

            }
            if (widget.type === 'info') {
                newWidgets.info.items.push(widget);
                if (newHead.find(e => e.type === 'info')) continue
                newWidgets.info.title = 'Info'
                newHead.push({type: 'info', title: 'Info'});

            }
            if (widget.type === 'action') {
                newWidgets.actions.items.push(widget);
                if (newHead.find(e => e.type === 'actions')) continue
                newWidgets.actions.title = 'Actions'
                newHead.push({type: 'actions', title: 'Actions'});

            }
            if (widget.type === 'link') {
                newWidgets.links.items.push(widget);
                if (newHead.find(e => e.type === 'links')) continue
                newWidgets.links.title = 'Fast links'
                newHead.push({type: 'links', title: 'Fast links'});

            }
            if (widget.type === 'custom') {
                newWidgets.custom.items.push(widget);
                if (newHead.find(e => e.type === 'custom')) continue
                newWidgets.custom.title = 'Custom'
                newHead.push({type: 'custom', title: 'Custom'});

            }
        }

        setWidgets(newWidgets);
        setHead(newHead);
    }, [initWidgets]);


    const filteredWidgets = useCallback(() => {
        if (filter && search.length < 1) {
            return {[filter]: widgets[filter]};
        } else if (search.length >= 1) {
            let newWidgets = {
                search: {
                    items: [] as Widget[],
                    title: 'Search',
                }
            };

            for (const key of Object.keys(widgets)) {
                const items = widgets[key].items.filter(e =>
                    e.name.toLowerCase().includes(search.toLowerCase())
                );
                newWidgets.search.items = [...newWidgets.search.items, ...items];
            }
            return newWidgets;
        } else {
            return widgets;
        }
    }, [widgets, filter, search]);

    return (
        <>
            <div className="flex flex-col gap-4 pl-1">
                <div className="flex gap-7 flex-wrap font-medium text-lg">
                    <div
                        className={`cursor-pointer hover:text-primary hover:underline transition-all ${!filter ? 'text-primary underline' : ''}`}
                        onClick={() => setFilter('')}>
                        All
                    </div>
                    {head.length > 0 && head.map((item: Head) => (
                        <div key={item.type}
                             className={`cursor-pointer hover:text-primary hover:underline transition-all ${filter === item.type ? 'text-primary underline' : ''}`}
                             onClick={() => setFilter(item.type)}>{item.title}</div>
                    ))}
                </div>
                <Input type="search" className="max-w-md" placeholder="Search" value={search}
                       onChange={(e) => setSearch(e.target.value)}/>
            </div>
            <div className="mt-6 flex flex-col gap-6">
                {Object.entries(filteredWidgets()).map(([key, widget]) => (
                    <div key={key}>
                        <h2 className="text-xl font-medium mb-4">{widget.title}</h2>
                        <div className="mt-2 grid grid-cols-4 gap-2">
                            {widget.items.map(item => (
                                <Card key={item.id} className="min-h-[225px] justify-between">
                                    <CardHeader>
                                        <CardTitle className="flex justify-between items-center">
                                            {item.name}
                                            <MaterialIcon name={item.icon} className="text-primary"/>
                                        </CardTitle>
                                    </CardHeader>
                                    <CardFooter className="justify-end">
                                        {item.added ? (
                                            <Button className="cursor-pointer" variant="secondary">Hide</Button>
                                        ) : (
                                            <Button className="cursor-pointer">Show</Button>
                                        )}
                                    </CardFooter>
                                </Card>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        </>
    )
}
export default addWidgets;

// src/assets/js/widgets/AddWidgets.vue
<template>
	<div class="add-widgets-pop-up" :class="block ? 'add-widgets-pop-up__block' : ''">
		<div class="add-widgets-pop-up__head">
			<h2>Widget Settings</h2>
		</div>
		<div class="add-widgets-pop-up__head-nav">
			<div class="add-widgets-pop-up__nav">
				<div class="add-widgets-pop-up__nav-item" :class="filter ? '' : 'add-widgets-pop-up__nav-item--active'"
					 @click="filter = null">
					<span>All</span>
				</div>
				<div class="add-widgets-pop-up__nav-item"
					 :class="filter === nav.type ? 'add-widgets-pop-up__nav-item--active' : ''"
					 v-for="nav in head" @click="filter = nav.type">
					<span>{{ nav.title }}</span>
				</div>
			</div>
			<input class="text-input" type="search" name="search" id="search" v-model="search">
		</div>
		<div class="add-widgets-pop-up__body">
			<div class="add-widgets-pop-up__widgets">
				<div class="add-widgets-pop-up__widgets-items" v-for="widget in filteredWidgets" :key="widget.title">
					<div class="add-widgets-pop-up__widgets-item">
						<h3>{{ widget.title }}</h3>
						<div class="add-widgets-pop-up__widgets-array">
							<div class="add-widgets-pop-up__widgets-array-item" v-for="item in widget.items"
								 :key="item.id">
								<div class="add-widgets-pop-up__widgets-array-item-top">
											<span class="add-widgets-pop-up__widgets-array-item-icon">
												<span class="material-icons-outlined">{{item.icon ?? 'widgets' }}</span>
												</span>
									<div class="add-widgets-pop-up__widgets-array-item-title">
										{{ item.name }}
									</div>
								</div>
								<div class="add-widgets-pop-up__widgets-array-item-bottom">
									<div class="add-widgets-pop-up__widgets-array-item-btn" v-if="!item.added"
										 @click="addWidget(item.id)">
										Show
									</div>
									<div class="add-widgets-pop-up__widgets-array-item-btn-added" v-else
										 @click="addWidget(item.id)">
										Hide
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	name: "AddWidgets",
	props: ['initWidgets', 'block'],
	emits: ['addWidgets'],
	data() {
		return {
			widgets: {
				switchers: {
					items: [],
					title: null
				},
				info: {
					items: [],
					title: null
				},
				actions: {
					items: [],
					title: null
				},
				links: {
					items: [],
					title: null
				},
				customs: {
					items: [],
					title: null
				}
			},
			head: [],
			selectedWidgets: [],
			filter: null,
			search: ''
		}
	},
	computed: {
		filteredWidgets() {
			if (this.filter && this.search.length < 3) {
				const filtered = Object.keys(this.widgets).filter(key => key === this.filter)
				return [this.widgets[filtered]]
			} else if (this.search.length >= 3) {
				this.filter = null
				let new_widgets = {
					search: {
						items: [],
						title: 'Search',
					}
				}
				for (const key of Object.keys(this.widgets)) {
					let items = this.widgets[key].items.filter(e => e.name.toLowerCase().indexOf(this.search) >= 0)
					new_widgets.search.items = [...new_widgets.search.items, ...items]
				}
				return new_widgets
			} else {
				return this.widgets
			}
		}
	},
	created() {
		console.log(this.initWidgets)
		for (const widget of this.initWidgets) {
			if (widget.type === 'switcher') {
				this.widgets.switchers.items.push(widget)
				if (this.head.find(e => e.type === 'switchers')) continue
				this.widgets.switchers.title = 'Switcher'
				this.head.push({
					type: 'switchers',
					title: 'Switcher'
				})
			}
			if (widget.type === 'info') {
				this.widgets.info.items.push(widget)
				if (this.head.find(e => e.type === 'info')) continue
				this.widgets.info.title = 'Info'
				this.head.push({
					type: 'info',
					title: 'Info'
				})
			}
			if (widget.type === 'action') {
				this.widgets.actions.items.push(widget)
				if (this.head.find(e => e.type === 'actions')) continue
				this.widgets.actions.title = 'Actions'
				this.head.push({
					type: 'actions',
					title: 'Actions'
				})
			}
			if (widget.type === 'link') {
				this.widgets.links.items.push(widget)
				if (this.head.find(e => e.type === 'links')) continue
				this.widgets.links.title = 'Links'
				this.head.push({
					type: 'links',
					title: 'Fast links'
				})
			}
			if (widget.type === 'custom') {
				this.widgets.customs.items.push(widget)
				if (this.head.find(e => e.type === 'custom')) continue
				this.widgets.customs.title = 'Customs'
				this.head.push({
					type: 'custom',
					title: 'Custom'
				})
			}
		}
	},
	methods: {
		addWidget(id) {
			for (const key of Object.keys(this.widgets)) {
				let item = this.widgets[key].items.find(e => e.id === id)
				if (item) item.added = !item.added
			}
			this.$emit('addWidgets', id)
		}
	},

}
</script>

<style scoped>


</style>
